name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.6.7', '9.8.2']
        cabal: ['3.10']

    steps:
    - uses: actions/checkout@v4

    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - name: Configure
      run: cabal configure --enable-tests
    - name: Dry run
      run: cabal build all --dry-run
    - name: Restore Cached Dependencies
      uses: actions/cache/restore@v4
      id: restore-deps-cache
      env:
        cache-name: cache-cabal
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-${{ hashFiles('**/plan.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Install dependencies
      run: |
        cabal build --only-dependencies --enable-tests --enable-benchmarks all
    - name: Save dependencies cache
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.setup.outputs.cabal-store }}
        key: ${{ steps.restore-deps-cache.outputs.cache-primary-key }}
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all

    - name: Run tests
      run: cabal test all
